"""baseline schema from sqlalchemy models

Revision ID: 0a265488d88f
Revises: 
Create Date: 2026-04-16 14:41:43.410604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a265488d88f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agronomist_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=50), nullable=False),
    sa.Column('problem', sa.String(length=100), nullable=False),
    sa.Column('tip_text_es', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ancestral_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_es', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('practice_type', sa.String(length=50), nullable=False),
    sa.Column('crops', sa.JSON(), nullable=False),
    sa.Column('benefits_es', sa.Text(), nullable=False),
    sa.Column('scientific_basis', sa.Text(), nullable=True),
    sa.Column('problems', sa.JSON(), nullable=True),
    sa.Column('applicable_months', sa.JSON(), nullable=True),
    sa.Column('timing_rationale', sa.Text(), nullable=True),
    sa.Column('ecological_benefit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cooperatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('family', sa.String(length=100), nullable=False),
    sa.Column('growing_season', sa.String(length=100), nullable=False),
    sa.Column('water_needs', sa.String(length=50), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=False),
    sa.Column('companions', sa.JSON(), nullable=False),
    sa.Column('days_to_harvest', sa.Integer(), nullable=True),
    sa.Column('optimal_temp_min', sa.Float(), nullable=True),
    sa.Column('optimal_temp_max', sa.Float(), nullable=True),
    sa.Column('description_es', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('crop_varieties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.Column('water_mm', sa.Integer(), nullable=True),
    sa.Column('diseases', sa.JSON(), nullable=False),
    sa.Column('adaptation_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_es', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.JSON(), nullable=False),
    sa.Column('affected_crops', sa.JSON(), nullable=False),
    sa.Column('treatments', sa.JSON(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('farmer_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=False),
    sa.Column('formal_term_es', sa.String(length=150), nullable=False),
    sa.Column('likely_cause', sa.String(length=200), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('crop', sa.String(length=50), nullable=True),
    sa.Column('symptom', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fertilizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_es', sa.Text(), nullable=False),
    sa.Column('application_method', sa.Text(), nullable=False),
    sa.Column('cost_per_ha_mxn', sa.Integer(), nullable=False),
    sa.Column('nutrient_profile', sa.String(length=200), nullable=False),
    sa.Column('suitable_crops', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('total_hectares', sa.Float(), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('cooperative_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('health_score_floor', sa.Float(), nullable=False),
    sa.Column('ndvi_minimum', sa.Float(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id')
    )
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('crop_type', sa.String(length=50), nullable=True),
    sa.Column('hectares', sa.Float(), nullable=True),
    sa.Column('planted_at', sa.DateTime(), nullable=True),
    sa.Column('boundary_coordinates', sa.JSON(), nullable=True),
    sa.Column('computed_area_hectares', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tek_adoptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('adopted_at', sa.DateTime(), nullable=False),
    sa.Column('fields_applied', sa.JSON(), nullable=False),
    sa.Column('farmer_notes_es', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tek_adoptions_farm_adopted', 'tek_adoptions', ['farm_id', 'adopted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('humidity_pct', sa.Float(), nullable=False),
    sa.Column('wind_kmh', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('forecast_3day', sa.JSON(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_records_farm_recorded', 'weather_records', ['farm_id', 'recorded_at'], unique=False)
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbon_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('soc_percent', sa.Float(), nullable=False),
    sa.Column('measurement_date', sa.String(length=10), nullable=False),
    sa.Column('lab_method', sa.String(length=100), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('observation_es', sa.Text(), nullable=False),
    sa.Column('observation_type', sa.String(length=20), nullable=False),
    sa.Column('crop_stage', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_farmer_observations_field_created', 'farmer_observations', ['field_id', 'created_at'], unique=False)
    op.create_table('field_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('drone_type', sa.String(length=50), nullable=True),
    sa.Column('mission_type', sa.String(length=50), nullable=True),
    sa.Column('flight_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('images_count', sa.Integer(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('s3_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=50), nullable=False),
    sa.Column('harvest_date', sa.DateTime(), nullable=False),
    sa.Column('actual_yield_kg', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_harvest_records_field_date', 'harvest_records', ['field_id', 'harvest_date'], unique=False)
    op.create_table('microbiome_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('respiration_rate', sa.Float(), nullable=False),
    sa.Column('microbial_biomass_carbon', sa.Float(), nullable=False),
    sa.Column('fungi_bacteria_ratio', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(length=30), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_snapshots_field_type', 'prediction_snapshots', ['field_id', 'prediction_type'], unique=False)
    op.create_table('soil_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('organic_matter_pct', sa.Float(), nullable=True),
    sa.Column('nitrogen_ppm', sa.Float(), nullable=True),
    sa.Column('phosphorus_ppm', sa.Float(), nullable=True),
    sa.Column('potassium_ppm', sa.Float(), nullable=True),
    sa.Column('texture', sa.String(length=50), nullable=True),
    sa.Column('moisture_pct', sa.Float(), nullable=True),
    sa.Column('electrical_conductivity', sa.Float(), nullable=True),
    sa.Column('depth_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('sampled_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_soil_analyses_field_sampled', 'soil_analyses', ['field_id', 'sampled_at'], unique=False)
    op.create_table('treatment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('health_score_used', sa.Float(), nullable=False),
    sa.Column('problema', sa.String(length=200), nullable=False),
    sa.Column('causa_probable', sa.String(length=300), nullable=False),
    sa.Column('tratamiento', sa.Text(), nullable=False),
    sa.Column('costo_estimado_mxn', sa.Integer(), nullable=False),
    sa.Column('urgencia', sa.String(length=20), nullable=False),
    sa.Column('prevencion', sa.Text(), nullable=False),
    sa.Column('organic', sa.Boolean(), nullable=False),
    sa.Column('ancestral_method_name', sa.String(length=100), nullable=True),
    sa.Column('ancestral_base_cientifica', sa.Text(), nullable=True),
    sa.Column('ancestral_razon_match', sa.String(length=300), nullable=True),
    sa.Column('timing_consejo', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('applied_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_treatment_records_field_applied', 'treatment_records', ['field_id', 'applied_at'], unique=False)
    op.create_table('farmer_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('treatment_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('worked', sa.Boolean(), nullable=False),
    sa.Column('farmer_notes', sa.Text(), nullable=True),
    sa.Column('alternative_method', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ndvi_mean', sa.Float(), nullable=True),
    sa.Column('ndvi_std', sa.Float(), nullable=True),
    sa.Column('thermal_max', sa.Float(), nullable=True),
    sa.Column('thermal_min', sa.Float(), nullable=True),
    sa.Column('stress_pct', sa.Float(), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('soil_organic_matter_pct', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_scores_field_scored', 'health_scores', ['field_id', 'scored_at'], unique=False)
    op.create_table('ndvi_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('ndvi_mean', sa.Float(), nullable=False),
    sa.Column('ndvi_std', sa.Float(), nullable=False),
    sa.Column('ndvi_min', sa.Float(), nullable=False),
    sa.Column('ndvi_max', sa.Float(), nullable=False),
    sa.Column('pixels_total', sa.Integer(), nullable=False),
    sa.Column('stress_pct', sa.Float(), nullable=False),
    sa.Column('zones', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ndvi_results_field_analyzed', 'ndvi_results', ['field_id', 'analyzed_at'], unique=False)
    op.create_table('thermal_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('temp_mean', sa.Float(), nullable=False),
    sa.Column('temp_std', sa.Float(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('pixels_total', sa.Integer(), nullable=False),
    sa.Column('stress_pct', sa.Float(), nullable=False),
    sa.Column('irrigation_deficit', sa.Boolean(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_thermal_results_field_analyzed', 'thermal_results', ['field_id', 'analyzed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thermal_results_field_analyzed', table_name='thermal_results')
    op.drop_table('thermal_results')
    op.drop_index('ix_ndvi_results_field_analyzed', table_name='ndvi_results')
    op.drop_table('ndvi_results')
    op.drop_index('ix_health_scores_field_scored', table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_table('farmer_feedback')
    op.drop_index('ix_treatment_records_field_applied', table_name='treatment_records')
    op.drop_table('treatment_records')
    op.drop_index('ix_soil_analyses_field_sampled', table_name='soil_analyses')
    op.drop_table('soil_analyses')
    op.drop_index('ix_prediction_snapshots_field_type', table_name='prediction_snapshots')
    op.drop_table('prediction_snapshots')
    op.drop_table('microbiome_records')
    op.drop_index('ix_harvest_records_field_date', table_name='harvest_records')
    op.drop_table('harvest_records')
    op.drop_table('flight_logs')
    op.drop_table('field_photos')
    op.drop_index('ix_farmer_observations_field_created', table_name='farmer_observations')
    op.drop_table('farmer_observations')
    op.drop_table('carbon_baselines')
    op.drop_table('alerts')
    op.drop_table('alert_logs')
    op.drop_index('ix_weather_records_farm_recorded', table_name='weather_records')
    op.drop_table('weather_records')
    op.drop_table('users')
    op.drop_index('ix_tek_adoptions_farm_adopted', table_name='tek_adoptions')
    op.drop_table('tek_adoptions')
    op.drop_table('fields')
    op.drop_table('alert_configs')
    op.drop_table('farms')
    op.drop_table('fertilizers')
    op.drop_table('farmer_vocabulary')
    op.drop_table('diseases')
    op.drop_table('crop_varieties')
    op.drop_table('crop_types')
    op.drop_table('cooperatives')
    op.drop_table('ancestral_methods')
    op.drop_table('agronomist_tips')
    # ### end Alembic commands ###
