"""API router registry — import modules, not individual routers."""

from cultivos.api import (
    alerts,
    auth,
    carbon,
    dashboard,
    disease,
    farms,
    feedback,
    flights,
    growth_stage,
    health,
    intel,
    intervention_scores,
    irrigation,
    knowledge,
    microbiome,
    missions,
    ndvi,
    reports,
    rotation,
    seasonal_alerts,
    soil,
    thermal,
    treatments,
    weather,
    yield_pred,
)

# Flat list of every APIRouter that app.py should mount.
all_routers = [
    alerts.router,
    auth.router,
    carbon.router,
    dashboard.router,
    disease.router,
    disease.disease_risk_router,
    farms.router,
    feedback.router,
    flights.router,
    growth_stage.router,
    health.router,
    intel.router,
    intel.seasonal_router,
    intervention_scores.router,
    irrigation.router,
    knowledge.router,
    microbiome.router,
    missions.router,
    ndvi.router,
    reports.router,
    rotation.router,
    seasonal_alerts.router,
    soil.router,
    thermal.router,
    treatments.router,
    weather.router,
    yield_pred.router,
]
