"""API router registry — import modules, not individual routers."""

from cultivos.api import (
    action_timeline,
    alert_config,
    alert_escalations,
    alert_history,
    alerts,
    anomalies,
    certification,
    completeness,
    cooperatives,
    coop_agenda_semanal,
    coop_annual_report,
    coop_data_completeness,
    coop_evidence_pack,
    coop_monthly_progress,
    coop_whatsapp_digest,
    crop_diversity,
    demo,
    auth,
    harvests,
    observations,
    carbon,
    dashboard,
    disease,
    economics,
    farmer_impact,
    farm_recommendations,
    farm_regen_milestones,
    farm_digest,
    farm_saludo_diario,
    farms,
    fields,
    feedback,
    field_calendar,
    field_disease_history,
    field_intervention_effectiveness,
    field_predictions,
    field_accion,
    field_alertas_criticas,
    field_resumen,
    field_trayectoria,
    field_weather_alert_history,
    treatment_cost_effectiveness,
    treatment_roi,
    flights,
    fodecijal_report,
    fusion,
    growth_stage,
    health,
    intel,
    intelligence,
    intervention_scores,
    irrigation,
    irrigation_efficiency,
    knowledge,
    microbiome,
    missions,
    ndvi,
    ndvi_health_correlation,
    notifications,
    phenology,
    photos,
    portfolio_report,
    regen_scorecard_export,
    regenerative,
    regions,
    reports,
    risk_map,
    rotation,
    seasonal_alerts,
    seasonal_comparison,
    soil,
    soil_amendment,
    status,
    system_health,
    tek_adoption,
    thermal,
    treatments,
    water_efficiency,
    weather,
    yield_pred,
)

# Routers explicitly mounted WITHOUT authentication. These are either:
#   - unauthenticated flows that must stay open (login, register)
#   - grant/demo-facing endpoints read by reviewers without credentials
#   - system health / readiness probes called by infra
# Everything else in `all_routers` is mounted with
# `dependencies=[Depends(get_current_user)]` in app.py, so when AUTH_ENABLED
# is true the route 401s on an unauthenticated caller. When AUTH_ENABLED is
# false the dependency returns None and behavior is unchanged for tests +
# demos. Per-route farm_id ownership enforcement is per-handler work still
# on the backlog (see docs/AUDIT_2026-04-16.md §3.4).
_PUBLIC_ROUTER_LIST = [
    auth.router,
    demo.router,
    status.router,
    system_health.router,
    fodecijal_report.router,
]
# APIRouter is not hashable — keep identity lookup via id().
PUBLIC_ROUTER_IDS = frozenset(id(r) for r in _PUBLIC_ROUTER_LIST)


def is_public_router(r) -> bool:
    return id(r) in PUBLIC_ROUTER_IDS

# Flat list of every APIRouter that app.py should mount.
all_routers = [
    action_timeline.router,
    alert_config.router,
    alert_escalations.router,
    alert_history.router,
    alerts.router,
    anomalies.router,
    auth.router,
    carbon.router,
    certification.router,
    carbon.farm_carbon_router,
    completeness.router,
    cooperatives.router,
    coop_agenda_semanal.router,
    coop_annual_report.router,
    coop_data_completeness.router,
    coop_evidence_pack.router,
    coop_monthly_progress.router,
    coop_whatsapp_digest.router,
    crop_diversity.router,
    dashboard.router,
    farmer_impact.router,
    farm_recommendations.router,
    demo.router,
    disease.router,
    disease.disease_risk_router,
    economics.router,
    risk_map.router,
    farm_regen_milestones.router,
    farm_digest.router,
    farm_saludo_diario.router,
    farms.router,
    fields.router,
    feedback.router,
    field_calendar.router,
    field_disease_history.router,
    field_intervention_effectiveness.router,
    field_predictions.router,
    field_resumen.router,
    field_accion.router,
    field_alertas_criticas.router,
    field_trayectoria.router,
    field_weather_alert_history.router,
    harvests.router,
    observations.router,
    treatment_cost_effectiveness.router,
    treatment_roi.router,
    fodecijal_report.router,
    fusion.router,
    flights.router,
    growth_stage.router,
    health.router,
    intel.router,
    intel.seasonal_router,
    intelligence.router,
    intervention_scores.router,
    irrigation.router,
    irrigation_efficiency.router,
    knowledge.router,
    microbiome.router,
    missions.router,
    ndvi.router,
    ndvi_health_correlation.router,
    notifications.router,
    phenology.router,
    photos.router,
    portfolio_report.router,
    regen_scorecard_export.router,
    regenerative.router,
    regions.router,
    reports.router,
    rotation.router,
    seasonal_alerts.router,
    seasonal_comparison.router,
    soil.router,
    soil_amendment.router,
    status.router,
    system_health.router,
    tek_adoption.router,
    thermal.router,
    treatments.router,
    water_efficiency.router,
    weather.router,
    yield_pred.router,
]
